/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoreFocusComponent: typeof import('./src/components/CoreFocusComponent.vue')['default']
    DreamsComponent: typeof import('./src/components/DreamsComponent.vue')['default']
    QuickNotePanel: typeof import('./src/components/QuickNotePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimelineComponent: typeof import('./src/components/TimelineComponent.vue')['default']
  }
}
